name: 🔖 Documentation update
description: Improve Documentation
title: "Docs: "
labels: ["📄 docs update"]
body:
  - type: textarea
    id: improve-docs
    attributes:
      label: What you want to add in the documentation?
      description: What are the things that you find it missing?
      placeholder: Add an appropriate descriptions
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      description: Add screenshots to see the demo
      placeholder: Add the required screenshots to explain problem
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: "Record"
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

        - label: I want to work on this issue
