name: ✨ Feature Request
description: Suggest a feature request
title: "Feat: "
labels: ["⭐ enhancement", "SWOC S4"]
body:
  - type: textarea
    id: what-feature
    attributes:
      label: What feature?
      placeholder: Add an appropriate descriptions
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      description: Add screenshots to see the demo
      placeholder: Add the required screenshots to explain problem
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: "Record"
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

        - label: I want to work on this issue
